apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ktbt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-ktbt@sha256:2fff3bbf093666f81f728ef73a711fb2a8506bc9fa9b235e74f388ad016ae425
        name: my-nodejs
        resources: {}
status: {}
